apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: grpc-dotnet-container
spec:
  replicas: 1
  selector:
    matchLabels:
      service: client
  template:
    metadata:
      labels:
        app: grpc-dotnet-container
        service: client
    spec:
      containers:
        - name: client
          image: docker.io/grpc-dotnet/container-client:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: BackendUrl
              value: http://server
---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: grpc-dotnet-container
    service: client
spec:
  type: NodePort
  ports:
    - port: 3200
      targetPort: 80
      protocol: TCP
      nodePort: 30008
  selector:
    service: client