apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: grpc-dotnet-container
spec:
  replicas: 1
  selector:
    matchLabels:
      service: server
  template:
    metadata:
      labels:
        app: weather-forecast
        service: server
    spec:
      containers:
        - name: server
          image: docker.io/grpc-dotnet/container-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: grpc-dotnet-container
    service: server
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: server